### ISSUE TITLE
Just a question..

### ISSUE THREAD

**Issue by lots0logs** [julianlam/nodebb-plugin-sso-wordpress#1]
@julianlam Sorry for posting this here, but looks like SSO is no longer enabled on http://community.nodebb.org and that's how I access my account (I don't want to create a new one :grimacing: )

How difficult would it be to SSO with WordPress but in the opposite direction where WordPress gets auth from NodeBB. Currently our forum and website are two separate logins and I really want to find a way to use a single sign on system between them. Any advice you could offer will be much appreciated. Thanks!

**Comment by julianlam** [comment]
SSO should be re-enabled on the NodeBB community now :smile: 

As for user auth going the *other* way, that's more difficult, as we don't have access to WP's methods, so it would be a WP plugin that'd need to be created :smile:

**Comment by lots0logs** [comment]
@julianlam I can handle the WordPress side of things. I'd be happy to share what I come up with. I am just not sure how to handle the NodeBB side :confused:

**Comment by julianlam** [comment]
Unfortunately there is no plugin that turns NodeBB into an OAuth
provider... yet :)

**Comment by lots0logs** [comment]
@julianlam are there any documented methods of logging a user in from a plugin in NodeBB?
