### ISSUE TITLE
Hook `filter:user.delete` is deprecated, please use an alternative

### ISSUE THREAD

**Issue by justvanbloom** [julianlam/nodebb-plugin-sso-wordpress#2]
Initializing NodeBB v0.9.1

[plugins/nodebb-plugin-sso-wordpress] Hook `filter:user.delete` is deprecated, please use an alternative
[plugins/load] The following plugins may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing. In the event of an unresponsive NodeBB caused by this plugin, run `./nodebb reset -p PLUGINNAME` to disable it.
* nodebb-plugin-sso-wordpress

**Comment by anandkumar** [comment]
I can confirm, this might be causing problem on my forum. Please fix it!!

**Comment by julianlam** [comment]
v1.0.1, thanks guys.
