### ISSUE TITLE
Templates directory defined but not found

### ISSUE THREAD

**Issue by usama54321** [julianlam/nodebb-plugin-sso-wordpress#3]
I am getting the following warning in my nodebb log

14/12 17:40 [20209] - [33mwarn[39m: [plugins/nodebb-plugin-sso-wordpress] A templates directory was defined for this plugin, but was not found.

Furthermore, I can't find the plugin settings page in my nodebb installation as a result.

Nodebb version: 0.9.2

**Comment by julianlam** [comment]
I cannot reproduce this issue, the plugin installs fine in v0.9.2 and the templates directory is correctly loaded. How did you install it?

**Comment by usama54321** [comment]
I copied over the folder into the node_modules directory and ran npm install in the plugin directory. After this, I activated the plugin in nodebb and reloaded nodebb.

**Comment by julianlam** [comment]
Copied over the folder? Where did you download the files from?

Suggested installation method is via ACP, or `npm install nodebb-plugin-sso-wordpress`.

**Comment by julianlam** [comment]
If you copied the files over, make sure the `static` directory also got copied over.

**Comment by usama54321** [comment]
I downloaded the zip file from github. Let me install it through npm. And yes, the static folder is present

**Comment by usama54321** [comment]
It's working now! I am sorry for bothering you. Thanks!
