### ISSUE TITLE
redirect to wordpress login page

### ISSUE THREAD

**Issue by kidswong999** [julianlam/nodebb-plugin-sso-wordpress#6]
Hi, when I open the **Automatically redirect guests to Wordpress SSO** toggle, it works. 
But what I want is :  when **the guests clicked the login button**, Automatically redirect guests to Wordpress SSO.
I dont know the hook about **the guests clicked the login button**.
Could you help me?

Thanks.

**Comment by julianlam** [comment]
If WordPress SSO is the only SSO option available, and you disable local login/registration in the ACP, the login button will route to WordPress.

**Comment by kidswong999** [comment]
Thanks!
I disabled local login/registration. And it works perfect!

👍
